---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageID: ami-a4c7edb2
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup

  # an elastic IP for our instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceID: !Ref MyInstance

  # our EC2 security Group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIP: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIP: 0.0.0.0/0

# Mappings are fixed varibles and differentiate bet env, regions and ami
# used mostly for region, az, aws account, env, ami etc.
#  RegionMap:
#    us-east-1:
#      "32": ami-6411e20e #32
#      "64": ami-7a11e213 #64
#    us-west-1:
#      - ami-c9c7978c
#      - ami-cfc7978a
#    eu-east-1:
#      - ami-37c2f643
#      - ami-31c2f645

#Resources
#  myEC2Instance:
#    Type: AWS::EC2::Instance
#    Properties:
#      ImageID: !FindInMap [RegionMap, !Ref "AWS::Region", 32]
#      InstanceType: t2.micro

# outputs are variables you can use in other templates
# you can't delete a stack if outputs are being used by another stack

#Outputs:
#  StackSSHSecurityGroup:
#    Description: The SSH Security Group for our EC2
#    Value: !Ref MyComapanyWideSSHSecurityGroup
#    Export:
#      Name: SSHSecurityGroup

# This is how to import the line 78 value
#Resources:
#  MySecureInstance:
#    Type: AWS::EC2::Instance
#    Properties:
#      AvailabilityZone: us-east-2a
#      ImageID: ami-a4c7edb2
#      InstanceType: t2.micro
#      SecurityGroups:
#        - !ImportValue SSHSecurityGroup


# Conditions are used to control creation of resources or outputs
# based on a condition.

#Conditions:
#  CreateProdResources: !Equal [ !Ref EnvType, prod]
# will create resources that match prod environment.

# use it in the syntax below
#Resources:
#  MountPoint:
#    Type: AWS::EC2::VolumeAttachment
#    Condition: CreateProdResources

# GetAtt is to get attributes of a service
#NewVolume:
#  Type: AWS::EC2::Volume
#  Condition: CreateProdResources
#  Properties:
#    Size: 100
#    AvailabilityZone:
#      !GetAtt EC2Instance.AvailabilityZone